#pragma once

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    APP_LANG_ID_FR = 0,
    APP_LANG_ID_EN,
    APP_LANG_ID_DE,
    APP_LANG_ID_ES,
} app_lang_id_t;

#if CONFIG_APP_LANG_FR
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_FR
#elif CONFIG_APP_LANG_EN
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_EN
#elif CONFIG_APP_LANG_DE
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_DE
#else
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_ES
#endif

#if CONFIG_APP_BOARD_REV_A
#define APP_BOARD_REVISION "BOARD_REV_A_ST7262"
#elif CONFIG_APP_BOARD_REV_B
#define APP_BOARD_REVISION "BOARD_REV_B_AXS15231B"
#else
#define APP_BOARD_REVISION "UNKNOWN"
#endif

#define APP_MAX_TERRARIUMS CONFIG_APP_MAX_TERRARIUMS
#define APP_AUTOSAVE_INTERVAL_S CONFIG_APP_AUTOSAVE_INTERVAL_S
#define APP_SD_PATH_MAX_LEN CONFIG_APP_SD_PATH_MAX_LEN
#define APP_DOC_READ_CHUNK_SIZE CONFIG_APP_DOC_READ_CHUNK_SIZE
#define APP_ASSET_CACHE_SIZE CONFIG_APP_ASSET_CACHE_SIZE

#ifdef __cplusplus
}
#endif
