#pragma once

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    APP_LANG_ID_FR = 0,
    APP_LANG_ID_EN,
    APP_LANG_ID_DE,
    APP_LANG_ID_ES,
} app_lang_id_t;

#if CONFIG_APP_LANG_FR
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_FR
#define APP_DEFAULT_LANGUAGE_CODE "fr"
#elif CONFIG_APP_LANG_EN
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_EN
#define APP_DEFAULT_LANGUAGE_CODE "en"
#elif CONFIG_APP_LANG_DE
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_DE
#define APP_DEFAULT_LANGUAGE_CODE "de"
#else
#define APP_DEFAULT_LANGUAGE APP_LANG_ID_ES
#define APP_DEFAULT_LANGUAGE_CODE "es"
#endif

#if CONFIG_APP_BOARD_REV_A
#define APP_BOARD_REVISION "BOARD_REV_A_ST7262"
#elif CONFIG_APP_BOARD_REV_B
#define APP_BOARD_REVISION "BOARD_REV_B_AXS15231B"
#else
#define APP_BOARD_REVISION "UNKNOWN"
#endif

#define APP_MAX_TERRARIUMS CONFIG_APP_MAX_TERRARIUMS
#define APP_AUTOSAVE_INTERVAL_S CONFIG_APP_AUTOSAVE_INTERVAL_S
#define APP_SD_PATH_MAX_LEN CONFIG_APP_SD_PATH_MAX_LEN
#define APP_DOC_READ_CHUNK_SIZE CONFIG_APP_DOC_READ_CHUNK_SIZE
#define APP_ASSET_CACHE_SIZE CONFIG_APP_ASSET_CACHE_SIZE
#define APP_SD_MOUNT_POINT CONFIG_APP_SD_MOUNT_POINT
#define APP_SD_SAVES_DIR CONFIG_APP_SD_SAVES_DIR
#define APP_SD_DOCS_DIR CONFIG_APP_SD_DOCS_DIR
#define APP_SD_I18N_DIR CONFIG_APP_SD_I18N_DIR
#define APP_DOCS_REGULATORY_DIR APP_SD_DOCS_DIR "/reglementaires"
#define APP_DOCS_SPECIES_DIR APP_SD_DOCS_DIR "/species"
#define APP_DOCS_GUIDES_DIR APP_SD_DOCS_DIR "/guides"
#define APP_I18N_DEFAULT_FILE APP_SD_I18N_DIR "/" APP_DEFAULT_LANGUAGE_CODE ".json"
#define APP_THEME_HIGH_CONTRAST CONFIG_APP_THEME_HIGH_CONTRAST

#ifdef __cplusplus
}
#endif
